### ISSUE TITLE
Compatibility with zig 0.13?

### ISSUE THREAD

**Issue by niteshbalusu11** [cztomsik/tokamak#6]
Is the library compatible with zig 0.13?

I am getting these errors:

<img width="1707" alt="Screenshot 2024-10-30 at 5 30 01 PM" src="https://github.com/user-attachments/assets/385df538-7e80-47c6-bceb-9f5a6c71adc1">

**Comment by niteshbalusu11** [comment]
Just tested with zig master branch and it works fine.

**Comment by cztomsik** [comment]
It requires zig-master (mainly because of decl literals)

I think the breaking point was here if you want to use older version but many nice things were added since then. https://github.com/cztomsik/tokamak/commit/ddc4a365b7b314e0f490958711095fdb045a12d5

**Comment by niteshbalusu11** [comment]
Thank you. I'll use the master branch.

**Comment by sc68cal** [comment]
I just tried using `0.14.0-dev.2851+b074fb7dd` and had a different compilation error, so I guess zig `master` broke something else since this issue was closed?

```
/home/scollins/.cache/zig/p/122045bde16e6d0dfb98ca9b623e56e3939570279dcebc07db21d9442b99d891bf03/src/meta.zig:56:36: error: no field named 'One' in enum 'builtin.Type.Pointer.Size'
        .pointer => |p| p.size == .One,
                                  ~^~~
/snap/zig/13470/lib/std/builtin.zig:623:26: note: enum declared here
        pub const Size = enum(u2) {
                         ^~~~
/home/scollins/.cache/zig/p/122045bde16e6d0dfb98ca9b623e56e3939570279dcebc07db21d9442b99d891bf03/src/injector.zig:21:36: note: called from here
        if (comptime !meta.isOnePtr(@TypeOf(ctx))) {
``` cd /home/scollins/.cache/zig/p/122045bde16e6d0dfb98ca9b623e56e3939570279dcebc07db21d9442b99d891bf03

**Comment by cztomsik** [comment]
should be fixed, it had to be something recent (next zig release is around the corner so they likely did few last breaking changes)
