### ISSUE TITLE
unable to acces  form other  machines on network or trought external ip adres only   localhost, 127.0.0.1   work

### ISSUE THREAD

**Issue by MartinAbilev** [cztomsik/tokamak#8]
gpt say :

It sounds like your Zig FTP Tokomac server on port 3001 is configured to only accept local requests, which is why it works with localhost:3001/api and 127.0.0.1:3001/api but not with external IP addresses like 195.168.1.27:3001/api or 77.38.218.82:3001/api.

do i miss somethin some setings maybe ???

**Comment by niteshbalusu11** [comment]
had to check the source code, but this is how you change the hostname and port.

```zig
    const server = try tk.Server.init(allocator, routes, .{ .listen = .{ .hostname = "0.0.0.0", .port = 5001 } });
    defer server.deinit();

    try server.start();
```

**Comment by MartinAbilev** [comment]
oo thnaks i changed   to 195.168.1.27   now it works amazing :)

**Comment by MartinAbilev** [comment]
done
